### ISSUE TITLE
About modify/update for other games. 

### ISSUE THREAD

**Issue by Berthog** [vn-tools/whale-tools#3]
Sorry, I guess you are bussy, but just if it's possible, could you explain how to modify this tools to do it works with different whale-based games? I tried just changing harsh key and original game name but still didn't worked on my game. Tested on: https://vndb.org/v22880
Thanks in advance. 
Uppdat: When I said that it ddidn't worked, I was mean the tools creates a new archive.dat but this one doesn't work, the game simply don't start.

**Comment by rr-** [comment]
Sorry I wrote these tools 7 years ago so I don't remember much of it.

**Comment by Berthog** [comment]
> Sorry I wrote these tools 7 years ago so I don't remember much of it.

Not even where the game saves the filenames?

**Comment by rr-** [comment]
Nope :)
